# configs/dockermin_full.toml
max_steps = 200
batch_size = 32
rollouts_per_example = 8
learning_rate = 5e-6
lora_alpha = 64
oversampling_factor = 1.5
max_async_level = 2
trajectory_strategy = "interleaved"

[sampling]
max_tokens = 1024
temperature = 1.0

[[env]]
id = "dockermin"

[model]
name = "Qwen/Qwen2.5-Coder-7B-Instruct"
max_lora_rank = 32

[model.experimental]
lora = true

[wandb]
project = "dockermin"
name = "full-200step"
entity = "vladtemian"

[checkpoints]
interval = 25
keep_cloud = 2

[infrastructure]
compute_size = "L"
